--Triggers


--AUTOINCREMEDNTO PARA LA TABLA AEROLINEA
CREATE SEQUENCE seq_id_aerolinea
START WITH 1
INCREMENT BY 1 
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_ai_aerolinea 
BEFORE INSERT ON aerolinea
FOR EACH ROW
BEGIN
    :NEW.id_aerolinea := seq_id_aerolinea.NEXTVAL;
END;

--AUTOINCREMEDNTO PARA LA TABLA AEROPUERTO
CREATE SEQUENCE seq_id_aeropuerto
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_ai_aeropuerto
BEFORE INSERT ON aeropuerto
FOR EACH ROW 
BEGIN 
    :NEW.id_aeropuerto := seq_id_aeropuerto.NEXTVAL;
END;

--AUTOINCREMEDNTO PARA LA TABLA PUERTA DE EMBARQUE
CREATE SEQUENCE seq_id_puertaemba
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_ai_puertaemb
BEFORE INSERT ON puerta_embarque
FOR EACH ROW 
BEGIN 
    :NEW.id_puerta := seq_id_puertaemba.NEXTVAL;
END;

--AUTOINCREMEDNTO PARA LA TABLA PUERTA DE EMBARQUE
CREATE SEQUENCE seq_id_avion
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_ai_avion
BEFORE INSERT ON avion
FOR EACH ROW 
BEGIN 
    :NEW.id_avion := seq_id_avion.NEXTVAL;
END;

--AUTOINCREMEDNTO PARA LA TABLA ASIENTOS
CREATE SEQUENCE seq_id_asientos
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_ai_asientos
BEFORE INSERT ON asientos
FOR EACH ROW 
BEGIN 
    :NEW.id_asientos := seq_id_asientos.NEXTVAL;
END;

--AUTOINCREMEDNTO PARA LA TABLA AVIONES
CREATE SEQUENCE seq_id_avion
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_ai_avion
BEFORE INSERT ON avion
FOR EACH ROW 
BEGIN 
    :NEW.id_avion := seq_id_avion.NEXTVAL;
END;

--AUTOINCREMEDNTO PARA LA TABLA RUTA
CREATE SEQUENCE seq_id_ruta
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_ai_ruta
BEFORE INSERT ON ruta
FOR EACH ROW 
BEGIN 
    :NEW.id_ruta := seq_id_ruta.NEXTVAL;
END;
